Api/create get user info
fc5y/user-backend pull request #10
Opened 2020-11-22 16:52 UTC by houtaru

2020-11-22 18:50 UTC, dothanhlam97 requested changes

2020-11-22 18:50 UTC, dothanhlam97 commented on controller/user.js
> +    res.status(201).json({
Chỗ này chắc có nhầm lẫn á em. Chắc phải return về 200 nếu thành công.
Nit: Em có thể define Status code 200 là biến constant rồi dùng luôn. Ở /utils/ e tạo 1 file tên là error_code. Cho SUCCESS = 200

2020-11-22 19:14 UTC, houtaru commented on controller/user.js
> +    res.status(201).json({
em bị nhầm error code. Em đã update lại rồi ạ.

2020-11-22 20:21 UTC, houtaru commented
Em mới fix lại lỗi error code và add thêm api update user ạ.

2020-11-23 02:38 UTC, merged

2020-11-23 07:47 UTC, dothanhlam97 commented
@houtaru  https://studio.apicur.io/ vẫn bị out of date em nhé