Add create/verify token
fc5y/user-backend pull request #29
Opened 2020-11-29 15:22 UTC by houtaru

2020-11-29 15:54 UTC, dothanhlam97 commented on controller/user.js
> +    expiresIn: "1800",
create a constant

2020-11-29 15:54 UTC, dothanhlam97 commented on controller/user.js
> +  verifyAccount,
api verify đâu em ơi :D

2020-11-29 15:54 UTC, dothanhlam97 commented on controller/user.js
> +const saltRounds = 10;
const SALT_ROUNDS = 10;

2020-11-29 16:36 UTC, dothanhlam97 commented on controller/user.js
> +  const id = getIdParam(req);
Check is_verified_email = True -> return BAD REQUEST

2020-12-01 18:03 UTC, dothanhlam97 commented on config/config.json
> +    "username": "fc5y",
Please don't change this file @houtaru

2020-12-01 18:04 UTC, houtaru commented
Fix above comment and refactor some code.

2020-12-01 20:02 UTC, dothanhlam97 commented on controller/user.js
> +        code: 3001,
define error code

2020-12-01 20:06 UTC, dothanhlam97 commented on controller/user.js
> +        code: 3001,
Resolved. Blocked by @ndkhaivn 's PR

2020-12-01 20:11 UTC, dothanhlam97 commented on controller/user.js
> +  console.log(id, token);
Remove console.log

2020-12-01 20:11 UTC, dothanhlam97 commented on controller/user.js
> +  const token = jsonwebtoken.sign({ id: id }, process.env.JWT_SECRET, {
jsonwebtoken.sign({ email: email }, process.env.JWT_SECRET,

2020-12-01 20:11 UTC, dothanhlam97 commented on controller/user.js
> +    expiresIn: "600000",
tạo constant

2020-12-01 20:11 UTC, dothanhlam97 commented on controller/user.js
> +    console.log(user);
Remove console.log

2020-12-01 20:14 UTC, dothanhlam97 commented on controller/user.js
> +            models.User.update(
Sử dụng findByPk(decoded.id)

2020-12-01 20:15 UTC, dothanhlam97 commented on controller/user.js
> +      where: { id: id },
sử dụng findByPk(id)

2020-12-01 20:15 UTC, dothanhlam97 requested changes
Good job em!

2020-12-02 02:38 UTC, houtaru commented on controller/user.js
> +      where: { id: id },
sao lại sự dụng findByPk(id) vậy chị ?

2020-12-02 05:08 UTC, houtaru commented on controller/user.js
> +            models.User.update(
chỗ này là sao vậy chị?

2020-12-02 09:40 UTC, dothanhlam97 approved these changes

2020-12-02 09:40 UTC, dothanhlam97 commented
Great job em! @houtaru  🙏🙏🤩🤩🤩🎉🎉🎉🎉

2020-12-02 09:41 UTC, merged