Be able to get the current user info
fc5y/user-backend pull request #35
Opened 2020-12-05 00:12 UTC by dothanhlam97

2020-12-05 04:03 UTC, hnngo requested changes

2020-12-05 04:03 UTC, hnngo commented on controller/user.js
> +  console.log(user_id);
Remove this

2020-12-05 04:03 UTC, hnngo commented on controller/user.js
> +  }
```suggestion
  const user_id = !req.params.id ? req.user.id : getIdParam(req)
```

2020-12-06 10:05 UTC, hnngo approved these changes

2020-12-06 10:07 UTC, ndkhaivn approved these changes

2020-12-06 10:31 UTC, merged