Database
fc5y/user-backend pull request #5
Opened 2020-11-09 16:35 UTC by houtaru

Update *user* schema to database follow below image:

![](https://i.imgur.com/RzB9Gb9.png)

2020-11-10 00:21 UTC, ndkhaivn commented
- Nên viết tên table ra luôn, ví dụ `user` thay vì User, `rating_history` thay vì Rating
- Table nào cũng phải có một auto inc `id` (rất hiếm khi bỏ `id` ra)
- `user_id` chứ không viết liền nhé
- `userid` theo table hiện tại không unique được, mình cần lưu lại nhiều lần cập nhật rating của một user mà

2020-11-10 15:12 UTC, houtaru commented
@ndkhaivn em đã update lại database.

2020-11-10 20:38 UTC, dothanhlam97 requested changes

2020-11-10 20:38 UTC, dothanhlam97 commented on models/user.js
> +			defaultValue: "Nguyen Van A"
Cái nào không có default value thì k nên để một giá trị rác như vậy. Nếu allowNull = false mà k có default value, lúc íinsert sẽ báo lỗi thôi. k nên insert gía trị sai.

2020-11-10 20:38 UTC, dothanhlam97 commented on models/user.js
> +			defaultValue: "abc@xyz.com",
bỏ default value

2020-11-10 20:38 UTC, dothanhlam97 commented on models/user.js
> +			defaultValue: "MaLhr2g3uWUuUu57FQn2xGPJ6k24UaVnY6amEuk8BvchStnqkNe9o9W5s6CnXLox",
bỏ default value

2020-11-10 20:38 UTC, dothanhlam97 commented on models/user.js
> -				is: /^\w{3,}$/
Email address validation: ^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$

2020-11-10 20:38 UTC, dothanhlam97 commented on models/user.js
> +		user_id: {
Sao chỉ có mỗi user id vậy em?

2020-11-16 08:10 UTC, dothanhlam97 commented
Thanks em for hard working on it @houtaru 
Cái này có cái PR migration làm rồi. Nên chắc chị close nhé.

2020-11-16 08:10 UTC, closed without merging