Set up db migration
fc5y/user-backend pull request #6
Opened 2020-11-11 09:00 UTC by dothanhlam97

Followed this guide to set up db and migration:
https://sequelize.org/master/manual/migrations.html

1. Added config file:
2. Use sequelize which is auto generated 
3. await db.sequelize.sync();-> remove force=True

In the next PR:
1.remove example-setup.js
2. use migration to init db

After running migration:

```

+-------------+--------------+------+-----+---------+-------+
| Field       | Type         | Null | Key | Default | Extra |
+-------------+--------------+------+-----+---------+-------+
| id          | char(36)     | NO   | PRI | NULL    |       |
| full_name   | varchar(255) | NO   | UNI | NULL    |       |
| email       | varchar(255) | NO   | UNI | NULL    |       |
| password    | varchar(255) | NO   | UNI | NULL    |       |
| school_name | varchar(255) | YES  | UNI | NULL    |       |
| createdAt   | datetime     | NO   |     | NULL    |       |
| updatedAt   | datetime     | NO   |     | NULL    |       |
+-------------+--------------+------+-----+---------+-------+
7 rows in set (0.03 sec)

```

GET /api/users
```
[{"id":"18b327de-0fdd-4b33-bc99-d955413590ba","full_name":"jack-sparrow","email":"testemail@gmail.com","password":"asadads","school_name":null,"createdAt":"2020-11-10T22:56:31.000Z","updatedAt":"2020-11-10T22:56:31.000Z"}]
```
Will set up Postman soon

2020-11-14 20:11 UTC, dothanhlam97 commented on config/config.json
> +  "development": {
@ndkhaivn config chị tạo cho có thôi. Feel free to change it.

2020-11-15 08:17 UTC, hnngo requested changes

2020-11-15 08:17 UTC, hnngo commented on migrations/20201114170749-create-user.js
> +      },
According to the design, seem like FE will call some api with `firstName` and `lastName`. Should we consider splitting this attribute `fullName` into `firstName` and `lastName` ? @dothanhlam97 @ndkhaivn 

![image](https://user-images.githubusercontent.com/43344276/99179993-5f585b80-275d-11eb-885b-20af146ca4df.png)

2020-11-15 14:13 UTC, ndkhaivn commented
Để em tạo tutorial rồi merge luôn

2020-11-16 02:11 UTC, merged